### PR TITLE
Add TypeScript typings.

### PR DESCRIPTION
**Pull request by odensc**

### CODE REVIEW

**Review by danbahrami — APPROVED** [review]
Thanks again @odensc I will include this in the same release as your previous PR, will hopefully get time today or tomorrow to re-release.

**Comment by odensc** [comment]
Hey @danbahrami! Don't mean to bug you, but is there any update on merging the PRs? 😄

**Comment by danbahrami** [comment]
Hey @odensc thanks for your work on this. I've now merged both your PR's, tagged a new release and published to NPM.

**Comment by odensc** [comment]
Great, thank you very much!

**Pull request merged**
